language: generic
services:
- docker
script:
- docker build -t computationalplantscience/arabidopsis-rosette-analysis -f Dockerfile .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push computationalplantscience/arabidopsis-rosette-analysis
